[project]
name = "life-lab"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "nicegui>=3.3.1",
]

[dependency-groups]
dev = ["pytest>=8.3.0"]
